kind: Deployment
apiVersion: apps/v1
metadata:
  name:  cga101g4
  labels:
    app:  cga101g4
    version: m1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cga101g4
  template:
    metadata:
      labels:
        app:  cga101g4
        version: m1
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name:  cga101g4
        image: bensnowheart/cga101g4:latest
#        image:  cga101g4:latest
        imagePullPolicy: Always
#        imagePullPolicy: IfNotPresent        
        ports:
            - containerPort: 8009
              protocol: TCP
            - containerPort: 8080
              protocol: TCP     
        env:
        - name: MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName:  cga101g4
              resource: requests.memory
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName:  cga101g4
              resource: limits.memory
        - name: hibernate.connection.url
          value: jdbc:mysql://mysql.bensnows-dev.svc.cluster.local:3306/cga101g4?serverTimezone=Asia/Taipei
        - name: REDIS_HOST
          value: redis.bensnows-dev.svc.cluster.local
        - name: MYSQL_DATASOURCE
          value: TestDB
        - name: MYSQL_DATABASE
          value: cga101g4
        - name: MYSQL_USER
          value: tibame
        - name: MYSQL_PASSWORD
          value: tibame
        - name: MYSQL_HOST
          value: mysql.bensnows-dev.svc.cluster.local
        - name: JAVA_OPTS
          value: >-
                -Djboss.bind.address=0.0.0.0  -Xms1G -Xmx1536m  
                -Dorg.wildfly.datasources.mysql.host=mysql.bensnows-dev.svc.cluster.local
                -Dhibernate.connection.url=jdbc:mysql://mysql.bensnows-dev.svc.cluster.local:3306/cga101g4
                -Djboss.node.name=node1
        resources:
          requests: 
            memory: 1Gi
            cpu: 500m
          limits: 
            memory: 1536Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cga101g4
    service: cga101g4
  name: cga101g4
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cga101g4
  sessionAffinity: None
  type: ClusterIP